# Generated by Django 5.1.2 on 2024-12-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
    ]
