# Generated by Django 5.1.2 on 2024-12-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'managed': True},
        ),
    ]
