# Generated by Django 5.1.2 on 2024-12-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_vendor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'managed': True},
        ),
    ]
